---
title: "Assignment 3"
subtitle: "Local MDS and ISOMAP"
author: "Alexander, Ulrik, Hannes"
date: "`r format(Sys.time(), '%d/%b/%Y')`"
output: 
   html_document:
    code_folding: hide
    theme: cerulean
    highlight: textmate
    number_sections: true
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "#>")
# setwd("/home/ajo/gitRepos/ML/nonLinDimRed")
library(ggplot2)
library(dplyr)
library(stops)
```

# Local MDS for Zero Digits

As in Assignment 2, we will consider only the zeros in the ZIP data set. 

```{r}
# Utility function to plot images. 
plot.zip <- function(x,use.first=FALSE, ...){
  x<-as.numeric(x)
  if (use.first){
    x.mat <- matrix(x,16,16)
  }else{
    x.mat <- matrix(x[-1],16,16)
  }
  image(1:16,1:16,x.mat[,16:1],
        col=gray(seq(1,0,l=12)))
  if (!use.first) title(x[1])
}

zip.train <- read.table("../unsup/zip.train")
zip.zeros <- zip.train %>% dplyr::filter(V1 == 0)
dim(zip.zeros)
delta <- dist(zip.zeros)
```

## 2-dimensional Configuration of the Data

Using parameters $k = 5$ and $\tau = 0.05$ in the function `stops::lmds`, a 2-dimensional configuration of the data is found. 

```{r}
lmbds.res <- lmds(as.matrix(delta), k = 5, tau = 0.05)
# BRuker veldig lang tid, trenger initial-verdi eller noe?
# Rekker ikke 책 se mer p책 dette n책, tok for lang tid 책 installere stops + dependencies
```


# ISOMAP for Zero Digits


